site_name: Orix


theme:
    name: material
    highlightjs: true



    features:
        - navigation.tabs
        - navigation.top

nav:
    - Home: index.md
    - Getting started:
        - Installation: home/index.md
    - Developper guide : 
        - Installation: home/index.md
        - Memory management : home/memory.md
    - Hardware guide :
        - I/O : home/hardware/i_o.md

