site_name: Orix

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - tables
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - git-revision-date

dev_addr: '172.27.7.150:8001'

theme:
    name: material
    highlightjs: true
#    icon:
#        admonition:
#            <type>: <icon> #

    palette:
        primary: red
    features:
        - navigation.tabs
        - navigation.top
        - content.tabs.link

nav:
    - Home: index.md
    - Getting started : menu.md
    - User guide :
        - Commands : commands/all.md
        - Floppy drive commands:
            - Bootfd: user_manual/bootfd.md
        - Shell guide :
            - Basic 11 commands: how-it-work/index.md
        - Software loader : home/loader/loader.md
        - Hardware manuals :
            - Ribbon cable: hardware/nappe.md
            - Plug voice synthetizer: hardware/synth_vocal_mea80900.md
            - Oric incompatibility: hardware/incompatibility_oric.md
            - Hardware issues: hardware/hardware_issues.md
        - Updates :
            - 2022.3: update/2022_3.md
            - 2022.4: update/2022_4.md
            - commands:
                - File: update/file/file.md
    - Developper guide :
        - Install: home/index.md
        - Memory management : home/memory.md
        - Build an Orix rom : home/buildrom.md
        - Build standalone Rom : home/buildstandalonerom.md
        - Generate a binary for sdcard/usb key: binaries/generateBinary.md
        - SDK for Assembly (Orixsdk):
            - Main usage: home/orixsdk.md
            - File operations:
                - fopen: home/orixsdk_macros/fopen.md
                - fread: home/orixsdk_macros/fread.md
                - fwrite: home/orixsdk_macros/fwrite.md
                - fclose: home/orixsdk_macros/fclose.md
                - mkdir: home/orixsdk_macros/mkdir.md
                - chdir: home/orixsdk_macros/chdir.md
                - getcwd: home/orixsdk_macros/chdir.md
                - unlink: home/orixsdk_macros/unlink.md
            - Text mode operations:
                - print: home/orixsdk_macros/print.md
                - cputc: home/orixsdk_macros/cputc.md
                - crlf: home/orixsdk_macros/crlf.md
                - scroll: home/orixsdk_macros/scroll.md
                - cursor: home/orixsdk_macros/cursor.md
                - setscreen: home/orixsdk_macros/setscreen.md
            - Memory operations:
                - malloc: home/orixsdk_macros/malloc.md
                - mfree: home/orixsdk_macros/mfree.md
            - Strings operations:
                - strncat: home/orixsdk_macros/strncat.md
                - strncpy: home/orixsdk_macros/strncpy.md
            - Command line operations:
                - initmainargs: home/orixsdk_macros/initmainargs.md
                - getmainargs: home/orixsdk_macros/getmainargs.md
            - Keyboards operations:
                - cgetc: home/orixsdk_macros/cgetc.md
            - Process operations:
                - exec: home/orixsdk_macros/exec.md

        - Generate man pages : home/buildman.md
        - cc65 : home/cc65.md
        - Binary header format : home/header.md
        - Joysticks management : home/joysticks.md
        - Cross development on real hardware : home/pizero_connection.md
        - Oricutron VS real hardware : home/oricutronvsreal.md
    - Hardware guide :
        - Memory: hardware/memory.md
        - I/O: hardware/i_o.md
        - Firmware informations : home/firmware.md
        - Joysticks: hardware/joysticks.md
        - Eeprom structure: hardware/eeprom_structure.md
    - Kernel guide:
        - Kernel: home/kernel.md
        - Primitives:
            - General list : kernel/primitives/index.md
            - By category:
                - Command line args:
                    - XMAINARGS: kernel/primitives/xmainargs.md
                - Files operations:
                    - XOPEN: kernel/primitives/xopen.md
                    - XCLOSE: kernel/primitives/xclose.md
                    - XFREAD: kernel/primitives/xfread.md
                    - XWRITE: kernel/primitives/xwrite.md
                    - XFSEEK: kernel/primitives/xfseek.md
                - Memory operations:
                    - XMALLOC: kernel/primitives/xmalloc.md
                    - XFREE: kernel/primitives/xfree.md
        - Boot sequence: how-it-work/binary_starts.md
    - Extra Libs :
        - Twilighte librairy : libs/twillib.md
extra_css:
    - stylesheets/extra.css
extra:
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/OrixTwil
        - icon: fontawesome/brands/youtube
          link: https://www.youtube.com/user/jede06600/videos
