site_name: Orix


theme:
    name: readthedocs
    highlightjs: true



    features:
        - navigation.tabs
        - navigation.top

nav:
    - Home: index.md
    - Getting started:
        - Installation: home/index.md
