site_name: Orix

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - tables
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

dev_addr: '192.168.1.103:8001'

theme:
    name: material
    highlightjs: true
    icon:
        admonition:
            <type>: <icon> # 

    palette:
        primary: red
    features:
        - navigation.tabs
        - navigation.top
        - content.tabs.link

nav:
    - Home: index.md
    - Getting started:
        - Installation: home/index.md
    - Developper guide : 
        - Installation: home/index.md
        - Memory management : home/memory.md
        - Build an Orix rom : home/buildrom.md
        - Build standalone Rom : home/buildstandalonerom.md
        - SDK for Assembly : home/orixsdk.md
        - Generate man pages : home/buildman.md
        - cc65 : home/cc65.md
        - Binary header format : home/header.md
        - Joysticks management : home/joysticks.md
        - Cross development on real hardware : home/pizero_connection.md
        - Oricutron VS real hardware : home/oricutronvsreal.md
    - Hardware guide :
        - I/O : hardware/i_o.md
        - Firmware informations : home/firmware.md
        - Joysticks: hardware/joysticks.md
        - Eeprom structure: hardware/eeprom_structure.md
    - User guide :
        - Commands : commands/all.md
        - Floppy drive commands:
            - Bootfd: user_manual/bootfd.md
        - Shell guide : 
            - Basic 11 commands: how-it-work/index.md
    - Kernel guide : 
        - Kernel : home/kernel.md
        - Primitives : kernel/primitives/index.md 
        - Boot sequence: how-it-work/binary_starts.md
    - Extra Libs :
        - Twilighte librairy : libs/twillib.md

